/******************************************************************************
*  Generated by PSoC Designer 5.1.2101.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "UART.h"
#include "UART_CLOCK.h"

#endif
